### PR TITLE
Upgrade to latest versions

### PR DESCRIPTION
**Pull request by elmariofredo**
RPi Firmware: 1.20200811
K3OS:  v0.11.0

Changes docker run realpath to PWD as it doesn't work in zsh.
Add examples so newcomers know where to start

### CODE REVIEW

**Comment by Nashluffy** [comment]
Did you encounter an issue with cgroups memory not being enabled? I am as well and I see you added a line in for `/boot/cmdline.txt`. I've tried adding it in and rebooting my Pi's but it doesn't seem to pickup on them...

**Comment by Nashluffy** [comment]
Just re-built images using your fork, fixed my issues with cgroups memory not being enabled. Thanks much!!

**Comment by Ognian** [comment]
@sgielen does something speak agains merging this?

**Comment by sgielen** [comment]
Hi all, sorry for not getting to this earlier. Thanks for this, @elmariofredo! I guess for `.`, `$PWD` always gives the realpath.

**Comment by elmariofredo** [comment]
@sgielen thanks! please take a look also on #26 to support docker image with built in bash scripts, so users doesn't have to clone this repo.

**Pull request merged**
